services:
  - type: web
    name: consultar-negocios
    env: docker
    region: oregon
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DEBUG
        value: False
    disk:
      name: data
      mountPath: /app/data
      sizeGB: 1
